[package]
name = "parsnip"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.99"
unicode-segmentation = "1.13.3"
wasm-bindgen = "0.2.122"
# wasmtime = {version = "45.0.1", default-features = false, features = ["runtime"]}

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
# panic = "abort"
# strip = true
